package: klxm_restricted
version: '2.0.0'
author: KLXM
supportpage: https://github.com/FriendsOfREDAXO/klxm_restricted
name: KLXM Restricted (Zentrale Rechte- und Benutzerverwaltung)

requires:
    redaxo: ^5.18
    php: ^8.4
    yform: ^5.0
    packages:
        mediapool: ^2.14

autoload:
    classes:
        KLXM\Restricted\: lib/Restricted/


page:
    title: KLXM Restricted
    perm: klxm_restricted[share]
    icon: rex-icon fa-lock
    subpages:
        matrix:
            title: Rechte-Matrix
            perm: admin
            icon: rex-icon fa-th
        users:
            title: Benutzer
            perm: admin
            icon: rex-icon fa-user
        sessions:
            title: Sessions
            perm: admin
            icon: rex-icon fa-clock-o
        requests:
            title: Zugriffsanfragen
            perm: admin
            icon: rex-icon fa-inbox
        roles:
            title: Rollen
            perm: admin
            icon: rex-icon fa-users
        pastebin:
            title: Pastebin
            perm: klxm_restricted[pastebin]
            icon: rex-icon fa-clipboard
        share_requests:
            title: Medienstatistik
            perm: klxm_restricted[share]
            icon: rex-icon fa-line-chart
        setup:
            title: Setup
            perm: admin
            icon: rex-icon fa-wrench
        settings:
            title: Einstellungen
            perm: admin
            icon: rex-icon fa-cogs
        editorial:
            title: Handbuch
            perm: klxm_restricted[share]
            subPath: editorial.md
        help:
            title: Hilfe
            perm: klxm_restricted[share]
            subPath: README.md
            itemClass: 'pull-right'

pages:
    mediapool/klxm_restricted_file_share:
        title: Dateiablage teilen
        perm: klxm_restricted[share]
        icon: rex-icon fa-files-o

permissions:
    - klxm_restricted[share]
    - klxm_restricted[pastebin]

