package: klxm_restricted
version: '1.0.0'
author: KLXM
supportpage: https://github.com/FriendsOfREDAXO/klxm_restricted
name: KLXM Restricted (Zentrale Rechte- und Benutzerverwaltung)

requires:
    redaxo: ^5.18
    php: ^8.4
    yform: ^5.0
    packages:
        mediapool: ^2.14

autoload:
    classes:
        KLXM\Restricted\: lib/Restricted/


page:
    title: KLXM Restricted
    perm: admin
    icon: rex-icon fa-lock
    subpages:
        matrix:
            title: Rechte-Matrix
            icon: rex-icon fa-th
        users:
            title: Benutzer
            icon: rex-icon fa-user
        sessions:
            title: Sessions
            icon: rex-icon fa-clock-o
        requests:
            title: Zugriffsanfragen
            icon: rex-icon fa-inbox
        roles:
            title: Rollen
            icon: rex-icon fa-users
        settings:
            title: Einstellungen
            icon: rex-icon fa-cogs
        pastebin:
            title: Pastebin
            icon: rex-icon fa-clipboard
        setup:
            title: Setup
            icon: rex-icon fa-wrench
        help:
            title: Hilfe
            subPath: README.md
            itemClass: 'pull-right'

pages:
    mediapool/klxm_restricted_share:
        title: Medien teilen
        perm: klxm_restricted[share]
        icon: rex-icon fa-share-alt

permissions:
    - klxm_restricted[share]
    - klxm_restricted[pastebin]

